FROM nginx:alpine
RUN apk add --no-cache curl jq
COPY nginx.conf /etc/nginx/nginx.conf
COPY src/main/resources/example-payloads.json /payloads.json
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
