services:
  api-1: &api
    build: .
    image: rinha-hello:latest
    environment:
      JAVA_OPTS: "-server -Xmx128m -XX:+UseSerialGC -XX:-TieredCompilation -XX:CompileThreshold=100 --enable-native-access=ALL-UNNAMED"
      EVENT_LOOP_POOL_SIZE: "2"
      INTERNAL_WARMUP_ROUNDS: "500"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "155MB"

  api-2:
    <<: *api

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-net
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

networks:
  rinha-net:
    driver: bridge
