
worker_processes 1;
worker_cpu_affinity auto;
worker_rlimit_nofile 65535;
error_log /dev/stderr crit;

events {
    use epoll;
    worker_connections 65535;
    accept_mutex off;
    multi_accept on;
}

http {
    tcp_nodelay on;
    keepalive_timeout 60;
    sendfile off;
    tcp_nopush off;
    access_log off;
    server_tokens off;

    upstream hello_backend {
        server api1:8080;
        server api2:8080;
        keepalive 256;
    }

    server {
        listen 80 default_server;
        server_name _;

        location / {
            proxy_pass http://hello_backend;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Connection "";
            proxy_set_header Proxy-Connection "";
            proxy_socket_keepalive on;
        }
    }
}
