Args = --enable-http \
       --enable-https \
       -H:+AddAllCharsets \
       -march=compatibility \
       -H:+UnlockExperimentalVMOptions \
       --initialize-at-build-time=org.apache.lucene \
       --initialize-at-run-time=io.netty.handler.codec.compression.ZstdOptions
